title: Aleksei C. Kundla
logo: "/images/alek_kundla_headshot.JPG?raw=true"
description: >
  Dedicated Computer Science and Engineering Undergraduate at The Ohio State University 
  <br><br>
  Full-Stack Developer with four years of experience across three companies
  <br><br>
  <a href="https://www.linkedin.com/in/akundla/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
